# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brendan Farrell's Blog
email: bfarrelldev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings and reflections on technology and the business of building
  technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bfarrell.github.io" # the base hostname & protocol for your site
twitter_username: bfarrell76
github_username:  bfarrell

# Build settings
markdown: kramdown
